### ISSUE TITLE
Move fetch_dependencies.py logic to setup.py

### ISSUE THREAD

**Issue by mgiammar** [sharhar/vkdispatch#2]
The `fetch_dependencies.py` script currently grabs required dependencies (repos and other executables). This functionality can be moved into the `setup.py` script where platform-dependent logic can also be incorporated into the install steps.

**Comment by sharhar** [comment]
fetch_dependencies.py is seperate from setup.py because the dependency fetching stage happens before we create the .tar archive containing the package and we want the dependencies to be included in the .tar
